title: Page
pages: true
files: true
fields:
  title:
    label: Title
    type: text
    icon: header
  
  cover:
    label: Cover image
    type: image
    help: Optional Cover Image

  text:
    label: Text
    type:  markdown
    header1: h3
    header2: h4
